# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0
before_install:
  - gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example --repo-update
script:
  - set -o pipefail && xcodebuild -workspace Example/RxPager.xcworkspace -scheme RxPager-Example -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -sdk iphonesimulator build test  | xcpretty -c
  - pod lib lint
